services:
  autobrr-distroless:
    image: ghcr.io/s0up4200/autobrr-distroless:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    container_name: autobrr-distroless
    volumes:
      - ./config:/config
    ports:
      - "7474:7474"
    user: 1000:1000
    #read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: unless-stopped
