name: Check for new versions

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest version from autobrr
        id: autobrr
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/autobrr/autobrr/releases/latest | jq -r .tag_name)
          echo "latest_version=${LATEST_VERSION}" >> $GITHUB_OUTPUT

      - name: Get current version
        id: current
        run: |
          CURRENT_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "current_version=${CURRENT_VERSION}" >> $GITHUB_OUTPUT

      - name: Install semver
        run: |
          curl -O https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x semver

      - name: Compare versions
        id: compare
        run: |
          if [ "${RESULT}" = "1" ]; then
            echo "needs_update=true" >> $GITHUB_OUTPUT
          else
            echo "needs_update=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.compare.outputs.needs_update == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          TAG_NAME="${{ steps.autobrr.outputs.latest_version }}"
          git tag -a ${TAG_NAME} -m "Release ${TAG_NAME}"
          git push --follow-tags origin ${TAG_NAME}
          sleep 15
          gh workflow run build.yaml --ref ${TAG_NAME}
